In [1]:
!pip install numpy
!pip install pandas

Collecting numpy
  Downloading numpy-1.24.3-cp310-cp310-win_amd64.whl (14.8 MB)
                                              0.0/14.8 MB ? eta -:--:--
                                              0.1/14.8 MB 1.1 MB/s eta 0:00:14
                                              0.2/14.8 MB 1.5 MB/s eta 0:00:10
     -                                        0.4/14.8 MB 2.8 MB/s eta 0:00:06
     -                                        0.7/14.8 MB 3.5 MB/s eta 0:00:05
     ---                                      1.2/14.8 MB 5.0 MB/s eta 0:00:03
     ----                                     1.7/14.8 MB 6.0 MB/s eta 0:00:03
     -----                                    2.2/14.8 MB 6.6 MB/s eta 0:00:02
     -------                                  2.8/14.8 MB 7.3 MB/s eta 0:00:02
     --------                                 3.3/14.8 MB 7.8 MB/s eta 0:00:02
     ----------                               3.8/14.8 MB 8.1 MB/s eta 0:00:02
     -----------                              4.3/14.8 MB 8.4 MB/s eta 0:00:02
     ------------                             4.7/14.8 MB 8.5 MB/s eta 0:00:02
     --------------                           5.3/14.8 MB 8.7 MB/s eta 0:00:02
     ---------------                          5.8/14.8 MB 8.9 MB/s eta 0:00:02
     -----------------                        6.3/14.8 MB 9.0 MB/s eta 0:00:01
     ------------------                       6.8/14.8 MB 9.1 MB/s eta 0:00:01
     -------------------                      7.1/14.8 MB 9.0 MB/s eta 0:00:01
     --------------------                     7.5/14.8 MB 8.9 MB/s eta 0:00:01
     ---------------------                    8.1/14.8 MB 9.0 MB/s eta 0:00:01
     -----------------------                  8.6/14.8 MB 9.2 MB/s eta 0:00:01
     ------------------------                 9.1/14.8 MB 9.3 MB/s eta 0:00:01
     -------------------------                9.6/14.8 MB 9.3 MB/s eta 0:00:01
     ---------------------------              10.1/14.8 MB 9.4 MB/s eta 0:00:01
     ---------------------------             10.6/14.8 MB 10.4 MB/s eta 0:00:01
     -----------------------------           11.1/14.8 MB 10.6 MB/s eta 0:00:01
     ------------------------------          11.7/14.8 MB 10.6 MB/s eta 0:00:01
     --------------------------------        12.2/14.8 MB 10.7 MB/s eta 0:00:01
     ---------------------------------       12.8/14.8 MB 10.7 MB/s eta 0:00:01
     -----------------------------------     13.4/14.8 MB 10.9 MB/s eta 0:00:01
     ------------------------------------    13.9/14.8 MB 10.9 MB/s eta 0:00:01
     -------------------------------------   14.4/14.8 MB 10.9 MB/s eta 0:00:01
     --------------------------------------  14.8/14.8 MB 10.9 MB/s eta 0:00:01
     --------------------------------------- 14.8/14.8 MB 10.4 MB/s eta 0:00:00
Installing collected packages: numpy
Successfully installed numpy-1.24.3
Collecting pandas
  Downloading pandas-2.0.2-cp310-cp310-win_amd64.whl (10.7 MB)
                                              0.0/10.7 MB ? eta -:--:--
                                              0.0/10.7 MB 1.4 MB/s eta 0:00:08
                                              0.1/10.7 MB 1.3 MB/s eta 0:00:09
                                              0.2/10.7 MB 1.9 MB/s eta 0:00:06
     -                                        0.5/10.7 MB 2.8 MB/s eta 0:00:04
     --                                       0.7/10.7 MB 3.2 MB/s eta 0:00:04
     ----                                     1.1/10.7 MB 4.2 MB/s eta 0:00:03
     ------                                   1.6/10.7 MB 5.1 MB/s eta 0:00:02
     --------                                 2.2/10.7 MB 6.1 MB/s eta 0:00:02
     ----------                               2.7/10.7 MB 6.7 MB/s eta 0:00:02
     ------------                             3.3/10.7 MB 7.3 MB/s eta 0:00:02
     --------------                           3.9/10.7 MB 7.7 MB/s eta 0:00:01
     ----------------                         4.4/10.7 MB 8.1 MB/s eta 0:00:01
     ------------------                       5.0/10.7 MB 8.4 MB/s eta 0:00:01
     --------------------                     5.5/10.7 MB 8.6 MB/s eta 0:00:01
     ----------------------                   6.1/10.7 MB 8.8 MB/s eta 0:00:01
     ------------------------                 6.6/10.7 MB 9.0 MB/s eta 0:00:01
     --------------------------               7.2/10.7 MB 9.2 MB/s eta 0:00:01
     -----------------------------            7.8/10.7 MB 9.3 MB/s eta 0:00:01
     -------------------------------          8.3/10.7 MB 9.5 MB/s eta 0:00:01
     ---------------------------------        8.8/10.7 MB 9.7 MB/s eta 0:00:01
     ----------------------------------       9.3/10.7 MB 9.6 MB/s eta 0:00:01
     -------------------------------------    9.9/10.7 MB 9.7 MB/s eta 0:00:01
     --------------------------------------  10.4/10.7 MB 10.7 MB/s eta 0:00:01
     --------------------------------------- 10.7/10.7 MB 11.1 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sandun\documents\ml\laptop price predictor\model\env\lib\site-packages (from pandas) (2.8.2)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2023.3-py2.py3-none-any.whl (502 kB)
Collecting tzdata>=2022.1 (from pandas)
  Using cached tzdata-2023.3-py2.py3-none-any.whl (341 kB)
Requirement already satisfied: numpy>=1.21.0 in c:\users\sandun\documents\ml\laptop price predictor\model\env\lib\site-packages (from pandas) (1.24.3)
Requirement already satisfied: six>=1.5 in c:\users\sandun\documents\ml\laptop price predictor\model\env\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Installing collected packages: pytz, tzdata, pandas
Successfully installed pandas-2.0.2 pytz-2023.3 tzdata-2023.3

In [200]:
import numpy as np
import pandas as pd

In [201]:
url = "https://raw.githubusercontent.com/dineshpiyasamara/LaptopPricePredictor/master/model%20building/laptop_price.csv"
data = pd.read_csv(url, encoding='latin-1')
data.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

In [202]:
data.shape

(1303, 12)

In [203]:
data.isnull()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
1298,False,False,False,False,False,False,False,False,False,False,False,False
1299,False,False,False,False,False,False,False,False,False,False,False,False
1300,False,False,False,False,False,False,False,False,False,False,False,False
1301,False,False,False,False,False,False,False,False,False,False,False,False
1302,False,False,False,False,False,False,False,False,False,False,False,False

In [204]:
data.isnull().sum()

laptop_ID           0
Company             0
Product             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Gpu                 0
OpSys               0
Weight              0
Price_euros         0
dtype: int64

In [243]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1302 entries, 0 to 1302
Data columns (total 32 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Ram                          1302 non-null   int32
 1   Weight                       1302 non-null   float32
 2   Price_euros                  1302 non-null   float64
 3   Touchscreen                  1302 non-null   int64
 4   Ips                          1302 non-null   int64
 5   Company_Acer                 1302 non-null   int32
 6   Company_Apple                1302 non-null   int32
 7   Company_Asus                 1302 non-null   int32
 8   Company_Dell                 1302 non-null   int32
 9   Company_HP                   1302 non-null   int32
 10  Company_Lenovo               1302 non-null   int32
 11  Company_MSI                  1302 non-null   int32
 12  Company_Other                1302 non-null   int32
 13  Company_Toshiba              1302 non-null   int32
 14  TypeName_2 in 1 Convertible  1302 non-null   int32
 15  TypeName_Gaming              1302 non-null   int32
 16  TypeName_Netbook             1302 non-null   int32
 17  TypeName_Notebook            1302 non-null   int32
 18  TypeName_Ultrabook           1302 non-null   int32
 19  TypeName_Workstation         1302 non-null   int32
 20  OpSys_Linux                  1302 non-null   int32
 21  OpSys_Mac                    1302 non-null   int32
 22  OpSys_Other                  1302 non-null   int32
 23  OpSys_Windows                1302 non-null   int32
 24  cpu_name_AMD                 1302 non-null   int32
 25  cpu_name_Intel Core i3       1302 non-null   int32
 26  cpu_name_Intel Core i5       1302 non-null   int32
 27  cpu_name_Intel Core i7       1302 non-null   int32
 28  cpu_name_Other               1302 non-null   int32
 29  gpu_name_AMD                 1302 non-null   int32
 30  gpu_name_Intel               1302 non-null   int32
 31  gpu_name_Nvidia              1302 non-null   int32
dtypes: float32(1), float64(1), int32(28), int64(2)
memory usage: 188.2 KB

In [206]:
data.head(2)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94

In [207]:
data['Ram'] = data['Ram'].str.replace('GB','').astype('int32')
data['Weight'] = data['Weight'].str.replace('kg','').astype('float32')

In [208]:
data.corr()['Price_euros']

ValueError: could not convert string to float: 'Apple'

In [209]:
data['Company'].value_counts()

Company
Dell         297
Lenovo       297
HP           274
Asus         158
Acer         103
MSI           54
Toshiba       48
Apple         21
Samsung        9
Razer          7
Mediacom       7
Microsoft      6
Xiaomi         4
Vero           4
Chuwi          3
Google         3
Fujitsu        3
LG             3
Huawei         2
Name: count, dtype: int64

In [210]:
len(data['Company'].value_counts())

19

In [211]:
def add_company(inpt):
    if inpt == 'Samsung' or inpt == 'Razer' or inpt == 'Mediacom' or inpt == 'Microsoft'or inpt == 'Xiaomi'or inpt == 'Vero'or inpt == 'Chuwi'or inpt == 'Google'or inpt == 'Fujitsu'or inpt == 'LG'or inpt == 'Huawei':
        return 'Other'
    else:
        return inpt

In [212]:
data['Company'] = data['Company'].apply(add_company)

In [213]:
data['Company'].value_counts()

Company
Dell       297
Lenovo     297
HP         274
Asus       158
Acer       103
MSI         54
Other       51
Toshiba     48
Apple       21
Name: count, dtype: int64

In [214]:
data['Product'].value_counts()

Product
XPS 13                                     30
Inspiron 3567                              29
250 G6                                     21
Legion Y520-15IKBN                         19
Vostro 3568                                19
                                           ..
15-bw007nv (A10-9620P/6GB/128GB/Radeon      1
SmartBook 130                               1
A541NA-GO342 (N3350/4GB/500GB/Linux)        1
17-X047na (i3-6006U/8GB/1TB/W10)            1
V330-15IKB (i5-8250U/4GB/500GB/FHD/W10)     1
Name: count, Length: 618, dtype: int64

In [215]:
len(data['Product'].value_counts())

618

In [216]:
data['TypeName'].value_counts()

TypeName
Notebook              727
Gaming                205
Ultrabook             196
2 in 1 Convertible    121
Workstation            29
Netbook                25
Name: count, dtype: int64

In [217]:
data['ScreenResolution'].value_counts()

ScreenResolution
Full HD 1920x1080                                507
1366x768                                         281
IPS Panel Full HD 1920x1080                      230
IPS Panel Full HD / Touchscreen 1920x1080         53
Full HD / Touchscreen 1920x1080                   47
1600x900                                          23
Touchscreen 1366x768                              16
Quad HD+ / Touchscreen 3200x1800                  15
IPS Panel 4K Ultra HD 3840x2160                   12
IPS Panel 4K Ultra HD / Touchscreen 3840x2160     11
4K Ultra HD / Touchscreen 3840x2160               10
4K Ultra HD 3840x2160                              7
Touchscreen 2560x1440                              7
IPS Panel 1366x768                                 7
IPS Panel Quad HD+ / Touchscreen 3200x1800         6
IPS Panel Retina Display 2560x1600                 6
IPS Panel Retina Display 2304x1440                 6
Touchscreen 2256x1504                              6
IPS Panel Touchscreen 2560x1440                    5
IPS Panel Retina Display 2880x1800                 4
IPS Panel Touchscreen 1920x1200                    4
1440x900                                           4
IPS Panel 2560x1440                                4
IPS Panel Quad HD+ 2560x1440                       3
Quad HD+ 3200x1800                                 3
1920x1080                                          3
Touchscreen 2400x1600                              3
2560x1440                                          3
IPS Panel Touchscreen 1366x768                     3
IPS Panel Touchscreen / 4K Ultra HD 3840x2160      2
IPS Panel Full HD 2160x1440                        2
IPS Panel Quad HD+ 3200x1800                       2
IPS Panel Retina Display 2736x1824                 1
IPS Panel Full HD 1920x1200                        1
IPS Panel Full HD 2560x1440                        1
IPS Panel Full HD 1366x768                         1
Touchscreen / Full HD 1920x1080                    1
Touchscreen / Quad HD+ 3200x1800                   1
Touchscreen / 4K Ultra HD 3840x2160                1
IPS Panel Touchscreen 2400x1600                    1
Name: count, dtype: int64

In [218]:
data['Touchscreen'] = data['ScreenResolution'].apply(lambda x:1 if 'Touchscreen' in x else 0)
data['Ips'] = data['ScreenResolution'].apply(lambda x:1 if 'IPS' in x else 0)

In [219]:
data.head(2)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Touchscreen,Ips
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,0,1
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,Intel HD Graphics 6000,macOS,1.34,898.94,0,0

In [220]:
data['Cpu'].value_counts()

Cpu
Intel Core i5 7200U 2.5GHz       190
Intel Core i7 7700HQ 2.8GHz      146
Intel Core i7 7500U 2.7GHz       134
Intel Core i7 8550U 1.8GHz        73
Intel Core i5 8250U 1.6GHz        72
                                ...
Intel Core M M3-6Y30 0.9GHz        1
AMD A9-Series 9420 2.9GHz          1
Intel Core i3 6006U 2.2GHz         1
AMD A6-Series 7310 2GHz            1
Intel Xeon E3-1535M v6 3.1GHz      1
Name: count, Length: 118, dtype: int64

In [221]:
data['cpu_name'] = data['Cpu'].apply(lambda x:" ".join(x.split()[0:3]))

In [222]:
data['cpu_name'].value_counts()

cpu_name
Intel Core i7               527
Intel Core i5               423
Intel Core i3               136
Intel Celeron Dual           80
Intel Pentium Quad           27
Intel Core M                 19
AMD A9-Series 9420           12
Intel Celeron Quad            8
AMD A6-Series 9220            8
AMD A12-Series 9720P          7
Intel Atom x5-Z8350           5
AMD A8-Series 7410            4
Intel Atom x5-Z8550           4
Intel Pentium Dual            3
AMD A9-Series 9410            3
AMD Ryzen 1700                3
AMD A9-Series A9-9420         2
AMD A10-Series 9620P          2
Intel Atom X5-Z8350           2
AMD E-Series E2-9000e         2
Intel Xeon E3-1535M           2
Intel Xeon E3-1505M           2
AMD E-Series 7110             2
AMD A10-Series 9600P          2
AMD A6-Series A6-9220         2
AMD A10-Series A10-9620P      2
AMD Ryzen 1600                1
Intel Atom x5-Z8300           1
AMD E-Series E2-6110          1
AMD FX 9830P                  1
AMD E-Series E2-9000          1
AMD A6-Series 7310            1
Intel Atom Z8350              1
AMD A12-Series 9700P          1
AMD A4-Series 7210            1
AMD FX 8800P                  1
AMD E-Series 9000e            1
Samsung Cortex A72&A53        1
AMD E-Series 9000             1
AMD E-Series 6110             1
Name: count, dtype: int64

In [223]:
def set_processor(name):
    if name == 'Intel Core i7' or name == 'Intel Core i5' or name == 'Intel Core i3':
        return name
    else:
        if name.split()[0] == 'AMD':
            return 'AMD'
        else:
            return 'Other'

In [224]:
data['cpu_name'] = data['cpu_name'].apply(set_processor)

In [225]:
data['cpu_name'].value_counts()

cpu_name
Intel Core i7    527
Intel Core i5    423
Other            155
Intel Core i3    136
AMD               62
Name: count, dtype: int64

In [226]:
data['Gpu'].value_counts()

Gpu
Intel HD Graphics 620      281
Intel HD Graphics 520      185
Intel UHD Graphics 620      68
Nvidia GeForce GTX 1050     66
Nvidia GeForce GTX 1060     48
                          ...
AMD Radeon R5 520            1
AMD Radeon R7                1
Intel HD Graphics 540        1
AMD Radeon 540               1
ARM Mali T860 MP4            1
Name: count, Length: 110, dtype: int64

In [227]:
data['gpu_name'] = data['Gpu'].apply(lambda x:" ".join(x.split()[0:1]))

In [228]:
data['gpu_name'].value_counts()

gpu_name
Intel     722
Nvidia    400
AMD       180
ARM         1
Name: count, dtype: int64

In [229]:
data.shape

(1303, 16)

In [230]:
data = data[data['gpu_name'] != 'ARM']

In [231]:
data.shape

(1302, 16)

In [232]:
data.head(2)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Touchscreen,Ips,cpu_name,gpu_name
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,0,1,Intel Core i5,Intel
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,Intel HD Graphics 6000,macOS,1.34,898.94,0,0,Intel Core i5,Intel

In [233]:
data['OpSys'].value_counts()

OpSys
Windows 10      1072
No OS             66
Linux             62
Windows 7         45
Chrome OS         26
macOS             13
Mac OS X           8
Windows 10 S       8
Android            2
Name: count, dtype: int64

In [234]:
def set_os(inpt):
    if inpt == 'Windows 10' or inpt == 'Windows 7' or inpt == 'Windows 10 S':
        return 'Windows'
    elif inpt == 'macOS' or inpt == 'Mac OS X':
        return 'Mac'
    elif inpt == 'Linux':
        return inpt
    else:
        return 'Other'

In [235]:
data['OpSys'] = data['OpSys'].apply(set_os)

C:\Users\Sandun\AppData\Local\Temp\ipykernel_15220\3013695878.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['OpSys'] = data['OpSys'].apply(set_os)

In [236]:
data['OpSys'].value_counts()

OpSys
Windows    1125
Other        94
Linux        62
Mac          21
Name: count, dtype: int64

In [237]:
data.head(2)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Touchscreen,Ips,cpu_name,gpu_name
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,Intel Iris Plus Graphics 640,Mac,1.37,1339.69,0,1,Intel Core i5,Intel
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,Intel HD Graphics 6000,Mac,1.34,898.94,0,0,Intel Core i5,Intel

In [238]:
data = data.drop(columns=['laptop_ID', 'Inches', 'Product', 'Cpu', 'Gpu', 'ScreenResolution'])

In [239]:
data.head()

,Company,TypeName,Ram,OpSys,Weight,Price_euros,Touchscreen,Ips,cpu_name,gpu_name
0,Apple,Ultrabook,8,Mac,1.37,1339.69,0,1,Intel Core i5,Intel
1,Apple,Ultrabook,8,Mac,1.34,898.94,0,0,Intel Core i5,Intel
2,HP,Notebook,8,Other,1.86,575.00,0,0,Intel Core i5,Intel
3,Apple,Ultrabook,16,Mac,1.83,2537.45,0,1,Intel Core i7,AMD
4,Apple,Ultrabook,8,Mac,1.37,1803.60,0,1,Intel Core i5,Intel

In [240]:
data = pd.get_dummies(data, dtype=int)

In [241]:
data.head()

,Ram,Weight,Price_euros,Touchscreen,Ips,Company_Acer,Company_Apple,Company_Asus,Company_Dell,Company_HP,...,OpSys_Other,OpSys_Windows,cpu_name_AMD,cpu_name_Intel Core i3,cpu_name_Intel Core i5,cpu_name_Intel Core i7,cpu_name_Other,gpu_name_AMD,gpu_name_Intel,gpu_name_Nvidia
0,8,1.37,1339.69,0,1,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0
1,8,1.34,898.94,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0
2,8,1.86,575.00,0,0,0,0,0,0,1,...,1,0,0,0,1,0,0,0,1,0
3,16,1.83,2537.45,0,1,0,1,0,0,0,...,0,0,0,0,0,1,0,1,0,0
4,8,1.37,1803.60,0,1,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [242]:
data.shape

(1302, 32)

In [255]:
X = data.drop('Price_euros', axis=1)
y = data['Price_euros']

In [256]:
X

,Ram,Weight,Touchscreen,Ips,Company_Acer,Company_Apple,Company_Asus,Company_Dell,Company_HP,Company_Lenovo,...,OpSys_Other,OpSys_Windows,cpu_name_AMD,cpu_name_Intel Core i3,cpu_name_Intel Core i5,cpu_name_Intel Core i7,cpu_name_Other,gpu_name_AMD,gpu_name_Intel,gpu_name_Nvidia
0,8,1.37,0,1,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
1,8,1.34,0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
2,8,1.86,0,0,0,0,0,0,1,0,...,1,0,0,0,1,0,0,0,1,0
3,16,1.83,0,1,0,1,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
4,8,1.37,0,1,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,4,1.80,1,1,0,0,0,0,0,1,...,0,1,0,0,0,1,0,0,1,0
1299,16,1.30,1,1,0,0,0,0,0,1,...,0,1,0,0,0,1,0,0,1,0
1300,2,1.50,0,0,0,0,0,0,0,1,...,0,1,0,0,0,0,1,0,1,0
1301,6,2.19,0,0,0,0,0,0,1,0,...,0,1,0,0,0,1,0,1,0,0
1302,4,2.20,0,0,0,0,1,0,0,0,...,0,1,0,0,0,0,1,0,1,0

In [257]:
y

0       1339.69
1        898.94
2        575.00
3       2537.45
4       1803.60
         ...
1298     638.00
1299    1499.00
1300     229.00
1301     764.00
1302     369.00
Name: Price_euros, Length: 1302, dtype: float64

In [253]:
!pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.2.2-cp310-cp310-win_amd64.whl (8.3 MB)
                                              0.0/8.3 MB ? eta -:--:--
                                              0.0/8.3 MB 1.3 MB/s eta 0:00:07
                                              0.1/8.3 MB 1.3 MB/s eta 0:00:07
                                              0.2/8.3 MB 1.3 MB/s eta 0:00:07
                                              0.2/8.3 MB 1.3 MB/s eta 0:00:07
     -                                        0.3/8.3 MB 1.3 MB/s eta 0:00:07
     -                                        0.4/8.3 MB 1.4 MB/s eta 0:00:06
     --                                       0.5/8.3 MB 1.4 MB/s eta 0:00:06
     --                                       0.6/8.3 MB 1.5 MB/s eta 0:00:06
     --                                       0.6/8.3 MB 1.6 MB/s eta 0:00:05
     ---                                      0.7/8.3 MB 1.7 MB/s eta 0:00:05
     ---                                      0.8/8.3 MB 1.6 MB/s eta 0:00:05
     ---                                      0.8/8.3 MB 1.6 MB/s eta 0:00:05
     ----                                     1.0/8.3 MB 1.6 MB/s eta 0:00:05
     -----                                    1.1/8.3 MB 1.6 MB/s eta 0:00:05
     -----                                    1.1/8.3 MB 1.6 MB/s eta 0:00:05
     ------                                   1.2/8.3 MB 1.7 MB/s eta 0:00:05
     ------                                   1.4/8.3 MB 1.7 MB/s eta 0:00:04
     -------                                  1.5/8.3 MB 1.7 MB/s eta 0:00:04
     -------                                  1.6/8.3 MB 1.8 MB/s eta 0:00:04
     --------                                 1.7/8.3 MB 1.8 MB/s eta 0:00:04
     --------                                 1.8/8.3 MB 1.8 MB/s eta 0:00:04
     ---------                                1.9/8.3 MB 1.9 MB/s eta 0:00:04
     ----------                               2.1/8.3 MB 2.0 MB/s eta 0:00:04
     ----------                               2.1/8.3 MB 2.0 MB/s eta 0:00:04
     ----------                               2.3/8.3 MB 2.0 MB/s eta 0:00:04
     -----------                              2.4/8.3 MB 2.0 MB/s eta 0:00:03
     ------------                             2.5/8.3 MB 2.0 MB/s eta 0:00:03
     ------------                             2.7/8.3 MB 2.0 MB/s eta 0:00:03
     --------------                           2.9/8.3 MB 2.1 MB/s eta 0:00:03
     ---------------                          3.2/8.3 MB 2.2 MB/s eta 0:00:03
     ----------------                         3.4/8.3 MB 2.3 MB/s eta 0:00:03
     -----------------                        3.6/8.3 MB 2.4 MB/s eta 0:00:02
     ------------------                       3.9/8.3 MB 2.5 MB/s eta 0:00:02
     --------------------                     4.2/8.3 MB 2.6 MB/s eta 0:00:02
     ---------------------                    4.4/8.3 MB 2.7 MB/s eta 0:00:02
     ----------------------                   4.7/8.3 MB 2.8 MB/s eta 0:00:02
     ------------------------                 5.0/8.3 MB 2.9 MB/s eta 0:00:02
     -------------------------                5.4/8.3 MB 3.0 MB/s eta 0:00:01
     ---------------------------              5.7/8.3 MB 3.1 MB/s eta 0:00:01
     -----------------------------            6.1/8.3 MB 3.2 MB/s eta 0:00:01
     ------------------------------           6.4/8.3 MB 3.3 MB/s eta 0:00:01
     --------------------------------         6.8/8.3 MB 3.5 MB/s eta 0:00:01
     ----------------------------------       7.2/8.3 MB 3.6 MB/s eta 0:00:01
     ------------------------------------     7.6/8.3 MB 3.7 MB/s eta 0:00:01
     --------------------------------------   8.0/8.3 MB 3.8 MB/s eta 0:00:01
     ---------------------------------------  8.3/8.3 MB 3.9 MB/s eta 0:00:01
     ---------------------------------------- 8.3/8.3 MB 3.8 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.17.3 in c:\users\sandun\documents\ml\laptop price predictor\model\env\lib\site-packages (from scikit-learn) (1.24.3)
Collecting scipy>=1.3.2 (from scikit-learn)
  Downloading scipy-1.10.1-cp310-cp310-win_amd64.whl (42.5 MB)
                                              0.0/42.5 MB ? eta -:--:--
                                              0.5/42.5 MB 10.5 MB/s eta 0:00:05
                                              0.9/42.5 MB 9.1 MB/s eta 0:00:05
     -                                        1.4/42.5 MB 9.6 MB/s eta 0:00:05
     -                                        1.7/42.5 MB 9.2 MB/s eta 0:00:05
     --                                       2.3/42.5 MB 9.6 MB/s eta 0:00:05
     --                                       2.7/42.5 MB 9.7 MB/s eta 0:00:05
     ---                                      3.3/42.5 MB 10.0 MB/s eta 0:00:04
     ---                                      3.7/42.5 MB 9.7 MB/s eta 0:00:04
     ---                                      4.2/42.5 MB 9.8 MB/s eta 0:00:04
     ----                                     4.6/42.5 MB 10.2 MB/s eta 0:00:04
     ----                                     5.1/42.5 MB 9.9 MB/s eta 0:00:04
     -----                                    5.6/42.5 MB 10.0 MB/s eta 0:00:04
     -----                                    6.1/42.5 MB 10.0 MB/s eta 0:00:04
     ------                                   6.6/42.5 MB 10.0 MB/s eta 0:00:04
     ------                                   7.1/42.5 MB 10.1 MB/s eta 0:00:04
     -------                                  7.7/42.5 MB 10.2 MB/s eta 0:00:04
     -------                                  8.2/42.5 MB 10.3 MB/s eta 0:00:04
     --------                                 8.5/42.5 MB 10.3 MB/s eta 0:00:04
     --------                                 9.2/42.5 MB 10.4 MB/s eta 0:00:04
     ---------                                9.7/42.5 MB 10.3 MB/s eta 0:00:04
     ---------                               10.2/42.5 MB 10.5 MB/s eta 0:00:04
     ---------                               10.7/42.5 MB 10.6 MB/s eta 0:00:04
     ----------                              11.3/42.5 MB 10.6 MB/s eta 0:00:03
     ----------                              11.8/42.5 MB 10.7 MB/s eta 0:00:03
     -----------                             12.3/42.5 MB 10.7 MB/s eta 0:00:03
     -----------                             12.7/42.5 MB 10.7 MB/s eta 0:00:03
     ------------                            13.3/42.5 MB 10.7 MB/s eta 0:00:03
     ------------                            13.8/42.5 MB 10.6 MB/s eta 0:00:03
     -------------                           14.4/42.5 MB 10.9 MB/s eta 0:00:03
     -------------                           14.9/42.5 MB 10.9 MB/s eta 0:00:03
     --------------                          15.5/42.5 MB 11.1 MB/s eta 0:00:03
     --------------                          16.1/42.5 MB 11.1 MB/s eta 0:00:03
     ---------------                         16.6/42.5 MB 11.3 MB/s eta 0:00:03
     ---------------                         17.2/42.5 MB 11.3 MB/s eta 0:00:03
     ----------------                        17.8/42.5 MB 11.3 MB/s eta 0:00:03
     ----------------                        18.4/42.5 MB 11.3 MB/s eta 0:00:03
     -----------------                       18.9/42.5 MB 11.5 MB/s eta 0:00:03
     -----------------                       19.5/42.5 MB 11.5 MB/s eta 0:00:03
     ------------------                      20.0/42.5 MB 11.5 MB/s eta 0:00:02
     ------------------                      20.5/42.5 MB 11.7 MB/s eta 0:00:02
     -------------------                     21.1/42.5 MB 11.7 MB/s eta 0:00:02
     -------------------                     21.7/42.5 MB 11.7 MB/s eta 0:00:02
     --------------------                    22.2/42.5 MB 11.7 MB/s eta 0:00:02
     --------------------                    22.7/42.5 MB 11.7 MB/s eta 0:00:02
     ---------------------                   23.4/42.5 MB 11.9 MB/s eta 0:00:02
     ---------------------                   23.8/42.5 MB 11.9 MB/s eta 0:00:02
     ----------------------                  24.4/42.5 MB 11.9 MB/s eta 0:00:02
     ----------------------                  25.0/42.5 MB 11.9 MB/s eta 0:00:02
     -----------------------                 25.6/42.5 MB 11.9 MB/s eta 0:00:02
     ------------------------                26.2/42.5 MB 12.1 MB/s eta 0:00:02
     ------------------------                26.8/42.5 MB 12.1 MB/s eta 0:00:02
     -------------------------               27.2/42.5 MB 12.1 MB/s eta 0:00:02
     -------------------------               27.7/42.5 MB 11.9 MB/s eta 0:00:02
     -------------------------               28.3/42.5 MB 12.1 MB/s eta 0:00:02
     --------------------------              28.9/42.5 MB 11.9 MB/s eta 0:00:02
     --------------------------              29.4/42.5 MB 11.9 MB/s eta 0:00:02
     ---------------------------             30.0/42.5 MB 12.1 MB/s eta 0:00:02
     ----------------------------            30.6/42.5 MB 11.9 MB/s eta 0:00:01
     ----------------------------            31.2/42.5 MB 11.9 MB/s eta 0:00:01
     -----------------------------           31.8/42.5 MB 11.9 MB/s eta 0:00:01
     -----------------------------           32.3/42.5 MB 11.9 MB/s eta 0:00:01
     ------------------------------          32.9/42.5 MB 11.9 MB/s eta 0:00:01
     ------------------------------          33.5/42.5 MB 11.9 MB/s eta 0:00:01
     -------------------------------         34.1/42.5 MB 12.1 MB/s eta 0:00:01
     -------------------------------         34.5/42.5 MB 12.1 MB/s eta 0:00:01
     --------------------------------        35.1/42.5 MB 11.9 MB/s eta 0:00:01
     --------------------------------        35.6/42.5 MB 11.9 MB/s eta 0:00:01
     ---------------------------------       36.0/42.5 MB 11.9 MB/s eta 0:00:01
     ---------------------------------       36.7/42.5 MB 11.9 MB/s eta 0:00:01
     ----------------------------------      37.2/42.5 MB 11.7 MB/s eta 0:00:01
     ----------------------------------      37.8/42.5 MB 11.9 MB/s eta 0:00:01
     -----------------------------------     38.3/42.5 MB 11.7 MB/s eta 0:00:01
     -----------------------------------     38.9/42.5 MB 11.9 MB/s eta 0:00:01
     ------------------------------------    39.4/42.5 MB 11.7 MB/s eta 0:00:01
     ------------------------------------    39.9/42.5 MB 11.9 MB/s eta 0:00:01
     -------------------------------------   40.4/42.5 MB 11.7 MB/s eta 0:00:01
     -------------------------------------   41.1/42.5 MB 11.7 MB/s eta 0:00:01
     --------------------------------------  41.6/42.5 MB 11.7 MB/s eta 0:00:01
     --------------------------------------  42.1/42.5 MB 11.7 MB/s eta 0:00:01
     --------------------------------------  42.5/42.5 MB 11.7 MB/s eta 0:00:01
     --------------------------------------  42.5/42.5 MB 11.7 MB/s eta 0:00:01
     --------------------------------------- 42.5/42.5 MB 10.7 MB/s eta 0:00:00
Collecting joblib>=1.1.1 (from scikit-learn)
  Downloading joblib-1.2.0-py3-none-any.whl (297 kB)
                                              0.0/298.0 kB ? eta -:--:--
     -------------------------------------- 298.0/298.0 kB 9.3 MB/s eta 0:00:00
Collecting threadpoolctl>=2.0.0 (from scikit-learn)
  Downloading threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
Successfully installed joblib-1.2.0 scikit-learn-1.2.2 scipy-1.10.1 threadpoolctl-3.1.0

In [258]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)

In [261]:
X_train.shape, X_test.shape

((976, 31), (326, 31))

In [262]:
def model_acc(model):
    model.fit(X_train, y_train)
    acc = model.score(X_test, y_test)
    print(str(model)+ ' --> ' +str(acc))

In [266]:
#choosing best model 
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
model_acc(lr)

from sklearn.linear_model import Lasso
lasso = Lasso()
model_acc(lasso)

from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor()
model_acc(dt)

from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor()
model_acc(rf)

#choose random forest

LinearRegression() --> 0.6712499116067456
Lasso() --> 0.6715814321073867
DecisionTreeRegressor() --> 0.6850623014301934
RandomForestRegressor() --> 0.8086972320044001

In [276]:
from sklearn.model_selection import GridSearchCV

parameters = {'n_estimators':[10, 50, 100],
              'criterion':['squared_error','absolute_error','poisson']}

grid_obj = GridSearchCV(estimator=rf, param_grid=parameters)

grid_fit = grid_obj.fit(X_train, y_train)

best_model = grid_fit.best_estimator_

best_model

RandomForestRegressor(criterion='absolute_error')

In [277]:
best_model.score(X_test, y_test)

0.8130050389531955

In [281]:
import pickle
with open('predictor.pickle', 'wb') as file:
    pickle.dump(best_model, file)

In [280]:
X_train.columns

Index(['Ram', 'Weight', 'Touchscreen', 'Ips', 'Company_Acer', 'Company_Apple',
       'Company_Asus', 'Company_Dell', 'Company_HP', 'Company_Lenovo',
       'Company_MSI', 'Company_Other', 'Company_Toshiba',
       'TypeName_2 in 1 Convertible', 'TypeName_Gaming', 'TypeName_Netbook',
       'TypeName_Notebook', 'TypeName_Ultrabook', 'TypeName_Workstation',
       'OpSys_Linux', 'OpSys_Mac', 'OpSys_Other', 'OpSys_Windows',
       'cpu_name_AMD', 'cpu_name_Intel Core i3', 'cpu_name_Intel Core i5',
       'cpu_name_Intel Core i7', 'cpu_name_Other', 'gpu_name_AMD',
       'gpu_name_Intel', 'gpu_name_Nvidia'],
      dtype='object')

In [284]:
pred_value = best_model.predict([[8, 1.3, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0]])
pred_value

C:\Users\Sandun\Documents\ML\Laptop Price Predictor\model\env\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([1227.8156])